#!/usr/bin/env bash
set -eu

while read remote; do
    branch="${remote#origin/}"
    git checkout "${branch}"
    git merge origin/master
done <<< "$(git branch -r | grep -Ev '(HEAD|master)')"
git push --all origin
git checkout master
